version: "3.8"

services:
  cosmosdb:
    image: mcr.microsoft.com/cosmosdb/linux/azure-cosmos-emulator:latest
    ports:
      - "127.0.0.1:8081:8081"
    environment:
      AZURE_COSMOS_EMULATOR_PARTITION_COUNT: 1
