name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  test-multicloud-nosql:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./multicloud-nosql
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Install dependencies
        run: npm install

      - name: Check code format
        run: npm run fmt-check

      - name: Run the unit tests
        run: npm run test:unit

      - name: Start the DynamoDB
        run: docker-compose up -d dynamodb

      - name: Run the AWS integration tests
        run: npm run test:aws

      - name: Stop the DynamoDB
        run: docker-compose down --remove-orphans --timeout 10 || true

      - name: Start the Cosmos DB
        run: docker-compose -f docker-compose.azure.yml up -d cosmosdb

      - name: Run the Azure integration tests
        run: npm run test:azure

      - name: Stop the Cosmos DB
        run: docker-compose down --remove-orphans --timeout 10 || true
